p8105_hw1_zg2582
================
Zaixin Gao (zg2582)
2026-09-25

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# Problem 1

## load penguins dataset

``` r
data("penguins", package = "palmerpenguins")
names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NAs    :2       NAs    :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NAs   : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NAs    :2         NAs    :2

this dataset contains 344 rows and 8 columns. The variables are:
species, island, bill_length_mm, bill_depth_mm, flipper_length_mm,
body_mass_g, sex, year. The mean of flipper length is 200.9. please see
more important values in message.

## scatterplot of flipper_length_mm vs. bill_length_mm

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + 
  geom_point()
```

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

![](p8105_hw1_zg2582_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

``` r
ggsave("penguin_scatterplot.pdf")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

There is a positive relationship overall, penguins with longer bills
tend to have longer flippers. And the three species form separate
clusters. Adelie has short bills and flippers, Chinstrap has long bills
and medium flippers, Gentoo has long bills and the longest flippers. 2
penguins with missing values weren’t plotted.

# Problem 2

## create df

``` r
set.seed(1)
problem2_df = tibble(
  samp = rnorm(10),
  samp_pos = samp > 0,
  vec_char = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
  vec_factor = factor(c("low", "low", "low", "mid", "mid", "mid", 
                        "high", "high", "high", "high"))
)
```

## get means

``` r
summary(problem2_df)
```

    ##       samp          samp_pos            vec_char  vec_factor
    ##  Min.   :-0.8356   Mode :logical   Length   :10   high:4    
    ##  1st Qu.:-0.5462   FALSE:4         N.unique :10   low :3    
    ##  Median : 0.2566   TRUE :6         N.blank  : 0   mid :3    
    ##  Mean   : 0.1322                   Min.nchar: 1             
    ##  3rd Qu.: 0.5537                   Max.nchar: 1             
    ##  Max.   : 1.5953

samp is numeric, so I got a full numeric summary. The mean is 0.1322.
samp_pos is logical, so R just counts FALSE and TRUE. vec_char is
character, so R only describe the text. There’s no mean reported.
vec_factor is factor, and R counts how many values are in each level.
There’s no mean here either.

\###cross check with mean()

``` r
mean(pull(problem2_df, samp))
```

    ## [1] 0.1322028

``` r
mean(pull(problem2_df, samp_pos))
```

    ## [1] 0.6

``` r
mean(pull(problem2_df, vec_char))
```

    ## Warning in mean.default(pull(problem2_df, vec_char)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

``` r
mean(pull(problem2_df, vec_factor))
```

    ## Warning in mean.default(pull(problem2_df, vec_factor)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

the mean of last two returned NA, matchs what i got from summary().

\##convert variables from one type to another

``` r
as.numeric(pull(problem2_df, samp_pos))
as.numeric(pull(problem2_df, vec_char))
as.numeric(pull(problem2_df, vec_factor))
```

What I observed: the logical mean works because R turns TRUE and FALSE
into 1 and 0. The character mean fails because letters can’t become
numbers. The factor mean fails because, even though factors are stored
as numbers, those codes are category labels.
